apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-test
spec:
  template:
    spec:
      restartPolicy: Always
      containers:
      - name: test
        image: test:latest
        imagePullPolicy: Never
        ports:
        - name: http
          protocol: TCP
          containerPort: 3000
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 3000
          timeoutSeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0