apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-test
spec:
  selector:
    matchLabels:
      {}
  template:
    spec:
      restartPolicy: Always
      containers:
      - name: code-test
        image: docker.pkg.github.com/budacom/proyecto-nn-2/success:latest
        imagePullPolicy: Always
        ports:
        - name: http
          protocol: TCP
          containerPort: 3000
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 3000
          timeoutSeconds: 2
      imagePullSecrets:
      - name: dockerconfigjson-github-com
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0